- include_tasks: install-required-packages.yml

- include_tasks: configure-ssh.yml
  when: configure_ssh == True

- include_tasks: logs-anonymization.yml
  when: anonymize_logs == True

- include_tasks: shell-history-cleaning.yml
  when: clear_shell_history == True

- include_tasks: configure-firewall.yml
  when: configure_firewall == True

- include_tasks: change-root-password.yml
  when: change_root_password == True
